### PR TITLE
Initial front-end revamp

### PR DESCRIPTION
**Pull request by sophia-moore**

### CODE REVIEW

**Comment by rheadixit** [comment]
Looks good I resolved one issue with merging the .html file

**Review by rheadixit — APPROVED** [review]

**Review by IvanSotomayor — APPROVED** [review]
Looks amazing!

**Comment by tc89585** [comment]
looks great!

**Review by tc89585 — COMMENTED** [review]
looks great!

**Review by sophia-moore — COMMENTED** [review]
More minor front-end changes.

**Pull request merged**
